"""empty message

Revision ID: 016e7c4c74a6
Revises: cabd21f4dbcd
Create Date: 2016-08-04 23:14:31.979277

"""

# revision identifiers, used by Alembic.
revision = '016e7c4c74a6'
down_revision = 'cabd21f4dbcd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_machine_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('machine_room_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cevlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('f', sa.String(length=2), nullable=False),
    sa.Column('s', sa.String(length=3), nullable=False),
    sa.Column('p', sa.String(length=3), nullable=False),
    sa.Column('ont_id', sa.String(length=3), nullable=False),
    sa.Column('cevlan', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cevlan_cevlan'), 'cevlan', ['cevlan'], unique=False)
    op.create_index(op.f('ix_cevlan_f'), 'cevlan', ['f'], unique=False)
    op.create_index(op.f('ix_cevlan_ont_id'), 'cevlan', ['ont_id'], unique=False)
    op.create_index(op.f('ix_cevlan_p'), 'cevlan', ['p'], unique=False)
    op.create_index(op.f('ix_cevlan_s'), 'cevlan', ['s'], unique=False)
    op.drop_column('machineroom_list', 'area')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('area', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cevlan_s'), table_name='cevlan')
    op.drop_index(op.f('ix_cevlan_p'), table_name='cevlan')
    op.drop_index(op.f('ix_cevlan_ont_id'), table_name='cevlan')
    op.drop_index(op.f('ix_cevlan_f'), table_name='cevlan')
    op.drop_index(op.f('ix_cevlan_cevlan'), table_name='cevlan')
    op.drop_table('cevlan')
    op.drop_table('area_machine_room')
    ### end Alembic commands ###
