"""empty message

Revision ID: 04774dbfeec2
Revises: 48b8a9657c72
Create Date: 2017-06-20 22:40:35.441713

"""

# revision identifiers, used by Alembic.
revision = '04774dbfeec2'
down_revision = '48b8a9657c72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('workorder_login_name', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['workorder_login_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'workorder_login_name')
    ### end Alembic commands ###
