"""empty message

Revision ID: 0ad524b13861
Revises: 817b5d52198d
Create Date: 2016-08-11 16:56:04.253219

"""

# revision identifiers, used by Alembic.
revision = '0ad524b13861'
down_revision = '817b5d52198d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pevlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('pevlan', sa.String(length=5), nullable=False),
    sa.Column('service_type', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pevlan_pevlan'), 'pevlan', ['pevlan'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pevlan_pevlan'), table_name='pevlan')
    op.drop_table('pevlan')
    ### end Alembic commands ###
