"""empty message

Revision ID: 0fe8aa07fde9
Revises: 841f9420543d
Create Date: 2016-12-15 15:27:35.736358

"""

# revision identifiers, used by Alembic.
revision = '0fe8aa07fde9'
down_revision = '841f9420543d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('call_record_detail', sa.Column('call_group', sa.String(length=32), nullable=True))
    #op.create_index(op.f('ix_call_record_detail_call_group'), 'call_record_detail', ['call_group'], unique=False)
    op.drop_constraint('call_record_detail_ibfk_1', 'call_record_detail', type_='foreignkey')
    op.drop_index('ix_call_record_detail_alarmId', table_name='call_record_detail')
    op.drop_column('call_record_detail', 'alarmId')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_record_detail', sa.Column('alarmId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('call_record_detail_ibfk_1', 'call_record_detail', 'alarm_record', ['alarmId'], ['id'])
    op.create_index('ix_call_record_detail_alarmId', 'call_record_detail', ['alarmId'], unique=False)
    op.drop_index(op.f('ix_call_record_detail_call_group'), table_name='call_record_detail')
    op.drop_column('call_record_detail', 'call_group')
    ### end Alembic commands ###
