"""empty message

Revision ID: 112f84ac7d55
Revises: d65dd2b49ad0
Create Date: 2016-07-24 17:32:38.616478

"""

# revision identifiers, used by Alembic.
revision = '112f84ac7d55'
down_revision = 'd65dd2b49ad0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mac_learned_by_ont', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mac_learned_by_ont', sa.Column('test', mysql.VARCHAR(collation='utf8_bin', length=10), nullable=True))
    ### end Alembic commands ###
