"""empty message

Revision ID: 1a193ec407f4
Revises: 0fe8aa07fde9
Create Date: 2016-12-20 21:38:54.226944

"""

# revision identifiers, used by Alembic.
revision = '1a193ec407f4'
down_revision = '0fe8aa07fde9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_syslog_alarm_log_seq',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_syslog_alarm_log_seq')
    ### end Alembic commands ###
