"""empty message

Revision ID: 2e61722a3b29
Revises: 0fd42a67381a
Create Date: 2016-12-06 22:26:52.945470

"""

# revision identifiers, used by Alembic.
revision = '2e61722a3b29'
down_revision = '0fd42a67381a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('callId', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_alarm_record_callId'), 'alarm_record', ['callId'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarm_record_callId'), table_name='alarm_record')
    op.drop_column('alarm_record', 'callId')
    ### end Alembic commands ###
