"""empty message

Revision ID: 31d105f12044
Revises: 28cf16e23f16
Create Date: 2017-01-17 11:14:03.368479

"""

# revision identifiers, used by Alembic.
revision = '31d105f12044'
down_revision = '28cf16e23f16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_desc', sa.Column('alarm_type', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_desc', 'alarm_type')
    ### end Alembic commands ###
