"""empty message

Revision ID: 3ce51927777b
Revises: 31d105f12044
Create Date: 2017-01-31 14:34:09.583283

"""

# revision identifiers, used by Alembic.
revision = '3ce51927777b'
down_revision = '31d105f12044'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_attended_time', sa.Column('day_adjust', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_attended_time', 'day_adjust')
    ### end Alembic commands ###
