"""empty message

Revision ID: 3e4ee9eaaeaa
Revises: 6d58871d74a0
Create Date: 2016-07-25 15:30:38.008238

"""

# revision identifiers, used by Alembic.
revision = '3e4ee9eaaeaa'
down_revision = '6d58871d74a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_interface'), 'account', ['interface'], unique=False)
    op.create_index(op.f('ix_account_mac'), 'account', ['mac'], unique=False)
    op.create_index(op.f('ix_account_sub_int'), 'account', ['sub_int'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_sub_int'), table_name='account')
    op.drop_index(op.f('ix_account_mac'), table_name='account')
    op.drop_index(op.f('ix_account_interface'), table_name='account')
    ### end Alembic commands ###
