"""empty message

Revision ID: 42cd4c9116ff
Revises: d370c5101939
Create Date: 2016-12-06 21:35:35.459531

"""

# revision identifiers, used by Alembic.
revision = '42cd4c9116ff'
down_revision = 'd370c5101939'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('calledTimes', sa.SmallInteger(), nullable=True))
    op.drop_column('alarm_record', 'called_record_id')
    op.drop_column('alarm_record', 'voice_notify_callback_id')
    op.add_column('call_record_detail', sa.Column('alarmId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_call_record_detail_alarmId'), 'call_record_detail', ['alarmId'], unique=False)
    op.create_foreign_key(None, 'call_record_detail', 'alarm_record', ['alarmId'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_record_detail', type_='foreignkey')
    op.drop_index(op.f('ix_call_record_detail_alarmId'), table_name='call_record_detail')
    op.drop_column('call_record_detail', 'alarmId')
    op.add_column('alarm_record', sa.Column('voice_notify_callback_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm_record', sa.Column('called_record_id', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True))
    op.drop_column('alarm_record', 'calledTimes')
    ### end Alembic commands ###
