"""empty message

Revision ID: 48b8a9657c72
Revises: 83f7a1045476
Create Date: 2017-04-18 13:20:58.830671

"""

# revision identifiers, used by Alembic.
revision = '48b8a9657c72'
down_revision = '83f7a1045476'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_configure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=20), nullable=False),
    sa.Column('api_params', sa.String(length=100), nullable=False),
    sa.Column('api_params_value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('duty_attended_time')
    op.drop_table('call_record_detail')
    op.drop_table('job_desc')
    op.drop_table('call_time_range')
    op.drop_table('duty_schedule')
    op.drop_table('token_record')
    op.drop_table('alarm_record')
    op.drop_table('ups_info')
    op.drop_table('pon_alarm_record')
    op.drop_table('voice_notify_callback')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_notify_callback',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('phoneNum', mysql.VARCHAR(collation='utf8_bin', length=15), nullable=True),
    sa.Column('state', mysql.VARCHAR(collation='utf8_bin', length=5), nullable=True),
    sa.Column('callId', mysql.VARCHAR(collation='utf8_bin', length=40), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('pon_alarm_record',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('device_name', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True),
    sa.Column('ip', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('frame', mysql.VARCHAR(collation='utf8_bin', length=2), nullable=True),
    sa.Column('slot', mysql.VARCHAR(collation='utf8_bin', length=2), nullable=True),
    sa.Column('port', mysql.VARCHAR(collation='utf8_bin', length=3), nullable=True),
    sa.Column('fail_times', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('last_fail_time', mysql.DATETIME(), nullable=True),
    sa.Column('last_recovery_time', mysql.DATETIME(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('alarmed_flag', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ups_info',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('oid_dict', mysql.VARCHAR(collation='utf8_bin', length=200), server_default=sa.text('\'{"status":"1.3.6.1.4.1.935.1.1.1.4.1.1.0","power_left":"1.3.6.1.4.1.935.1.1.1.2.2.1.0"}\''), nullable=True),
    sa.Column('ip', mysql.VARCHAR(collation='utf8_bin', length=24), nullable=True),
    sa.Column('vendeor', mysql.VARCHAR(collation='utf8_bin', length=20), server_default=sa.text("'Megatech'"), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.Column('community', mysql.VARCHAR(collation='utf8_bin', length=20), server_default=sa.text("'shfkwg1221'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('alarm_record',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.VARCHAR(collation='utf8_bin', length=4096), nullable=True),
    sa.Column('content_md5', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('alarm_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('alarm_level', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('state', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('calledTimes', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('lastCallId', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True),
    sa.Column('call_group', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('token_record',
    sa.Column('unique_id', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('expire', mysql.VARCHAR(collation='utf8_bin', length=10), nullable=True),
    sa.PrimaryKeyConstraint('unique_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('duty_schedule',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_time', sa.DATE(), nullable=True),
    sa.Column('userid', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.Column('attended_time_id', mysql.SMALLINT(display_width=100), autoincrement=False, nullable=False),
    sa.Column('duty_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('priority', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('call_time_range',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('range_name', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('stop_time', mysql.TIME(), nullable=False),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('job_desc',
    sa.Column('job_id', mysql.VARCHAR(collation='utf8_bin', length=5), nullable=False),
    sa.Column('job_name', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.Column('job_desc', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True),
    sa.Column('alarm_type', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('call_record_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('phoneNum', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.Column('respCode', mysql.VARCHAR(collation='utf8_bin', length=10), nullable=True),
    sa.Column('callId', mysql.VARCHAR(collation='utf8_bin', length=40), nullable=True),
    sa.Column('createDateInResp', mysql.VARCHAR(collation='utf8_bin', length=15), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('call_group', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('duty_attended_time',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attended_time_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('stop_time', mysql.TIME(), nullable=False),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('day_adjust', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('api_configure')
    ### end Alembic commands ###
