"""empty message

Revision ID: 587d599dc829
Revises: 0ad524b13861
Create Date: 2016-08-11 17:02:08.097830

"""

# revision identifiers, used by Alembic.
revision = '587d599dc829'
down_revision = '0ad524b13861'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_port', sa.Column('pevlan', sa.String(length=5), nullable=False))
    op.create_index(op.f('ix_service_port_pevlan'), 'service_port', ['pevlan'], unique=False)
    op.drop_index('ix_service_port_outvlan', table_name='service_port')
    op.drop_column('service_port', 'outvlan')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_port', sa.Column('outvlan', mysql.VARCHAR(collation='utf8_bin', length=5), nullable=False))
    op.create_index('ix_service_port_outvlan', 'service_port', ['outvlan'], unique=False)
    op.drop_index(op.f('ix_service_port_pevlan'), table_name='service_port')
    op.drop_column('service_port', 'pevlan')
    ### end Alembic commands ###
