"""empty message

Revision ID: 644c576a4edc
Revises: 3e4ee9eaaeaa
Create Date: 2016-08-02 22:17:38.796217

"""

# revision identifiers, used by Alembic.
revision = '644c576a4edc'
down_revision = '3e4ee9eaaeaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ont_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f', sa.String(length=2), nullable=False),
    sa.Column('s', sa.String(length=3), nullable=False),
    sa.Column('p', sa.String(length=3), nullable=True),
    sa.Column('ont_id', sa.String(length=3), nullable=False),
    sa.Column('mac', sa.String(length=28), nullable=False),
    sa.Column('ontinfo_id', sa.Integer(), nullable=True),
    sa.Column('ont_model', sa.String(length=20), nullable=True),
    sa.Column('cevlan', sa.String(length=5), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('user_addr', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('regist_status', sa.SmallInteger(), nullable=True),
    sa.Column('reporter_name', sa.String(length=32), nullable=True),
    sa.Column('reporter_group', sa.String(length=32), nullable=True),
    sa.Column('regist_operator', sa.String(length=32), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ont_register_f'), 'ont_register', ['f'], unique=False)
    op.create_index(op.f('ix_ont_register_mac'), 'ont_register', ['mac'], unique=False)
    op.create_index(op.f('ix_ont_register_ont_id'), 'ont_register', ['ont_id'], unique=False)
    op.create_index(op.f('ix_ont_register_p'), 'ont_register', ['p'], unique=False)
    op.create_index(op.f('ix_ont_register_s'), 'ont_register', ['s'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ont_register_s'), table_name='ont_register')
    op.drop_index(op.f('ix_ont_register_p'), table_name='ont_register')
    op.drop_index(op.f('ix_ont_register_ont_id'), table_name='ont_register')
    op.drop_index(op.f('ix_ont_register_mac'), table_name='ont_register')
    op.drop_index(op.f('ix_ont_register_f'), table_name='ont_register')
    op.drop_table('ont_register')
    ### end Alembic commands ###
