"""empty message

Revision ID: 68dfa6cfefec
Revises: cfc16a7cc692
Create Date: 2016-12-04 00:40:49.054549

"""

# revision identifiers, used by Alembic.
revision = '68dfa6cfefec'
down_revision = 'cfc16a7cc692'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_notify_callback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.String(length=15), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('callId', sa.String(length=40), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notify_callback_phoneNum'), 'voice_notify_callback', ['phoneNum'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_notify_callback_phoneNum'), table_name='voice_notify_callback')
    op.drop_table('voice_notify_callback')
    ### end Alembic commands ###
