"""empty message

Revision ID: 73235d8cd3b1
Revises: bc72c09617b3
Create Date: 2016-09-05 09:41:38.717538

"""

# revision identifiers, used by Alembic.
revision = '73235d8cd3b1'
down_revision = 'bc72c09617b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('sync_func', sa.String(100), nullable=True),
    sa.Column('sync_device', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_sync_event_sub_id'), 'sync_event', ['sub_id'], unique=False)
    op.create_index(op.f('ix_sync_event_sync_func'), 'sync_event', ['sync_func'], unique=False)
    op.add_column('pevlan', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('service_port', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('service_port', 'update_time')
    op.drop_column('pevlan', 'update_time')
    op.drop_index(op.f('ix_sync_event_sync_func'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_sub_id'), table_name='sync_event')
    op.drop_table('sync_event')
    ### end Alembic commands ###
