"""init db

Revision ID: 75ccae4a5d08
Revises: None
Create Date: 2016-07-24 11:05:20.262171

"""

# revision identifiers, used by Alembic.
revision = '75ccae4a5d08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.Column('interface', sa.String(length=10), nullable=True),
    sa.Column('sub_int', sa.String(length=5), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('mac', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('machine_room_id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=28), nullable=False),
    sa.Column('customer_number', sa.String(length=64), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_operator'), 'log', ['operator'], unique=False)
    op.create_table('mac_learned_by_ont',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ont_mac', sa.String(length=30), nullable=False),
    sa.Column('learned_mac', sa.String(length=30), nullable=True),
    sa.Column('ontinfo_id', sa.String(length=7), nullable=True),
    sa.Column('device_id', sa.String(length=2), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mac_learned_by_ont_learned_mac'), 'mac_learned_by_ont', ['learned_mac'], unique=False)
    op.create_index(op.f('ix_mac_learned_by_ont_ont_mac'), 'mac_learned_by_ont', ['ont_mac'], unique=False)
    op.create_table('machineroom_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('device_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=30), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=False),
    sa.Column('login_name', sa.String(length=20), nullable=False),
    sa.Column('login_password', sa.String(length=20), nullable=False),
    sa.Column('machine_room_id', sa.Integer(), nullable=True),
    sa.Column('enable_password', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_room_id'], ['machineroom_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ont_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('f', sa.String(length=2), nullable=False),
    sa.Column('s', sa.String(length=3), nullable=False),
    sa.Column('p', sa.String(length=3), nullable=True),
    sa.Column('ont_id', sa.String(length=3), nullable=False),
    sa.Column('mac', sa.String(length=28), nullable=False),
    sa.Column('control_flag', sa.String(length=30), nullable=True),
    sa.Column('run_state', sa.String(length=30), nullable=True),
    sa.Column('config_state', sa.String(length=30), nullable=True),
    sa.Column('match_state', sa.String(length=30), nullable=True),
    sa.Column('protect_side', sa.String(length=10), nullable=True),
    sa.Column('rx_optical_power', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('olt_rx_ont_optical_power', sa.Float(), nullable=True),
    sa.Column('last_down_cause', sa.String(length=30), nullable=True),
    sa.Column('last_up_time', sa.DateTime(), nullable=True),
    sa.Column('last_down_time', sa.DateTime(), nullable=True),
    sa.Column('line_profile_id', sa.String(length=20), nullable=True),
    sa.Column('line_profile_name', sa.String(length=20), nullable=True),
    sa.Column('server_profile_id', sa.String(length=20), nullable=True),
    sa.Column('server_profile_name', sa.String(length=20), nullable=True),
    sa.Column('ont_status', sa.SmallInteger(), nullable=False),
    sa.Column('pre_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ont_detail_device_id'), 'ont_detail', ['device_id'], unique=False)
    op.create_index(op.f('ix_ont_detail_f'), 'ont_detail', ['f'], unique=False)
    op.create_index(op.f('ix_ont_detail_mac'), 'ont_detail', ['mac'], unique=False)
    op.create_index(op.f('ix_ont_detail_ont_id'), 'ont_detail', ['ont_id'], unique=False)
    op.create_index(op.f('ix_ont_detail_p'), 'ont_detail', ['p'], unique=False)
    op.create_index(op.f('ix_ont_detail_s'), 'ont_detail', ['s'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ont_detail_s'), table_name='ont_detail')
    op.drop_index(op.f('ix_ont_detail_p'), table_name='ont_detail')
    op.drop_index(op.f('ix_ont_detail_ont_id'), table_name='ont_detail')
    op.drop_index(op.f('ix_ont_detail_mac'), table_name='ont_detail')
    op.drop_index(op.f('ix_ont_detail_f'), table_name='ont_detail')
    op.drop_index(op.f('ix_ont_detail_device_id'), table_name='ont_detail')
    op.drop_table('ont_detail')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('device_list')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('machineroom_list')
    op.drop_index(op.f('ix_mac_learned_by_ont_ont_mac'), table_name='mac_learned_by_ont')
    op.drop_index(op.f('ix_mac_learned_by_ont_learned_mac'), table_name='mac_learned_by_ont')
    op.drop_table('mac_learned_by_ont')
    op.drop_index(op.f('ix_log_operator'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_table('account')
    ### end Alembic commands ###
