"""empty message

Revision ID: 817b5d52198d
Revises: b555e9dbac3f
Create Date: 2016-08-09 22:55:42.047875

"""

# revision identifiers, used by Alembic.
revision = '817b5d52198d'
down_revision = 'b555e9dbac3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ont_register', sa.Column('status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ont_register', 'status')
    ### end Alembic commands ###
