"""empty message

Revision ID: 83f7a1045476
Revises: 3ce51927777b
Create Date: 2017-02-01 00:07:58.642118

"""

# revision identifiers, used by Alembic.
revision = '83f7a1045476'
down_revision = '3ce51927777b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_schedule', sa.Column('priority', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_schedule', 'priority')
    ### end Alembic commands ###
