"""empty message

Revision ID: 841f9420543d
Revises: f24fa64b1859
Create Date: 2016-12-15 14:51:42.337592

"""

# revision identifiers, used by Alembic.
revision = '841f9420543d'
down_revision = 'f24fa64b1859'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('call_group', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_alarm_record_call_group'), 'alarm_record', ['call_group'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarm_record_call_group'), table_name='alarm_record')
    op.drop_column('alarm_record', 'call_group')
    ### end Alembic commands ###
