"""empty message

Revision ID: 8524175e2324
Revises: 04774dbfeec2
Create Date: 2017-06-22 15:12:18.875103

"""

# revision identifiers, used by Alembic.
revision = '8524175e2324'
down_revision = '04774dbfeec2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_name', sa.String(length=50), nullable=False),
    sa.Column('machine_room_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_community_name'), 'community', ['community_name'], unique=False)
    op.create_index(op.f('ix_community_machine_room_id'), 'community', ['machine_room_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_machine_room_id'), table_name='community')
    op.drop_index(op.f('ix_community_community_name'), table_name='community')
    op.drop_table('community')
    ### end Alembic commands ###
