"""empty message

Revision ID: 96a73b0d9b98
Revises: a64e2d8f011f
Create Date: 2016-12-26 00:10:35.676323

"""

# revision identifiers, used by Alembic.
revision = '96a73b0d9b98'
down_revision = 'a64e2d8f011f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pon_alarm_record', sa.Column('alarmed_flag', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pon_alarm_record', 'alarmed_flag')
    ### end Alembic commands ###
