"""empty message

Revision ID: 994fdbd937fc
Revises: a7140ffe879e
Create Date: 2016-12-04 15:39:25.470495

"""

# revision identifiers, used by Alembic.
revision = '994fdbd937fc'
down_revision = 'a7140ffe879e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_record', 'expire')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_record', sa.Column('expire', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
