"""empty message

Revision ID: 9e8d840c836e
Revises: bc75b6256aa7
Create Date: 2016-08-15 00:26:09.306904

"""

# revision identifiers, used by Alembic.
revision = '9e8d840c836e'
down_revision = 'bc75b6256aa7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'permit_value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('permit_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
