"""empty message

Revision ID: 9e98fc383784
Revises: 2e61722a3b29
Create Date: 2016-12-06 22:28:18.293672

"""

# revision identifiers, used by Alembic.
revision = '9e98fc383784'
down_revision = '2e61722a3b29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('lastCallId', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_alarm_record_lastCallId'), 'alarm_record', ['lastCallId'], unique=False)
    op.drop_index('ix_alarm_record_callId', table_name='alarm_record')
    op.drop_column('alarm_record', 'callId')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('callId', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True))
    op.create_index('ix_alarm_record_callId', 'alarm_record', ['callId'], unique=False)
    op.drop_index(op.f('ix_alarm_record_lastCallId'), table_name='alarm_record')
    op.drop_column('alarm_record', 'lastCallId')
    ### end Alembic commands ###
