"""empty message

Revision ID: a64e2d8f011f
Revises: 1a193ec407f4
Create Date: 2016-12-21 16:11:19.721287

"""

# revision identifiers, used by Alembic.
revision = 'a64e2d8f011f'
down_revision = '1a193ec407f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pon_alarm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('frame', sa.String(length=2), nullable=True),
    sa.Column('slot', sa.String(length=2), nullable=True),
    sa.Column('port', sa.String(length=3), nullable=True),
    sa.Column('fail_times', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('last_fail_time', sa.DateTime(), nullable=True),
    sa.Column('last_recovery_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('last_syslog_alarm_log_seq')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_syslog_alarm_log_seq',
    sa.Column('seq', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('pon_alarm_record')
    ### end Alembic commands ###
