"""empty message

Revision ID: a7140ffe879e
Revises: e4669e6d52d6
Create Date: 2016-12-04 15:35:38.519656

"""

# revision identifiers, used by Alembic.
revision = 'a7140ffe879e'
down_revision = 'e4669e6d52d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_attended_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attended_time_name', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('attended_time_id', sa.Integer(), nullable=False),
    sa.Column('duty_status', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_record',
    sa.Column('unique_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_record')
    op.drop_table('duty_schedule')
    op.drop_table('duty_attended_time')
    ### end Alembic commands ###
