"""empty message

Revision ID: b555e9dbac3f
Revises: 6423d8ac2e21
Create Date: 2016-08-08 12:26:51.953856

"""

# revision identifiers, used by Alembic.
revision = 'b555e9dbac3f'
down_revision = '6423d8ac2e21'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_port', sa.Column('port_status', sa.String(length=5), nullable=False))
    op.create_index(op.f('ix_service_port_port_status'), 'service_port', ['port_status'], unique=False)
    op.drop_index('ix_service_port_ont_id', table_name='service_port')
    op.drop_column('service_port', 'ont_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_port', sa.Column('ont_id', mysql.VARCHAR(collation='utf8_bin', length=3), nullable=False))
    op.create_index('ix_service_port_ont_id', 'service_port', ['ont_id'], unique=False)
    op.drop_index(op.f('ix_service_port_port_status'), table_name='service_port')
    op.drop_column('service_port', 'port_status')
    ### end Alembic commands ###
