"""empty message

Revision ID: b668f3526768
Revises: 016e7c4c74a6
Create Date: 2016-08-07 15:59:43.515613

"""

# revision identifiers, used by Alembic.
revision = 'b668f3526768'
down_revision = '016e7c4c74a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('f', sa.String(length=2), nullable=False),
    sa.Column('s', sa.String(length=3), nullable=False),
    sa.Column('p', sa.String(length=3), nullable=False),
    sa.Column('ont_id', sa.String(length=3), nullable=False),
    sa.Column('vlan_range', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_port_f'), 'service_port', ['f'], unique=False)
    op.create_index(op.f('ix_service_port_ont_id'), 'service_port', ['ont_id'], unique=False)
    op.create_index(op.f('ix_service_port_p'), 'service_port', ['p'], unique=False)
    op.create_index(op.f('ix_service_port_s'), 'service_port', ['s'], unique=False)
    op.create_index(op.f('ix_service_port_vlan_range'), 'service_port', ['vlan_range'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_port_vlan_range'), table_name='service_port')
    op.drop_index(op.f('ix_service_port_s'), table_name='service_port')
    op.drop_index(op.f('ix_service_port_p'), table_name='service_port')
    op.drop_index(op.f('ix_service_port_ont_id'), table_name='service_port')
    op.drop_index(op.f('ix_service_port_f'), table_name='service_port')
    op.drop_table('service_port')
    ### end Alembic commands ###
