"""empty message

Revision ID: b68a4f5e063d
Revises: 9e98fc383784
Create Date: 2016-12-09 23:03:28.460901

"""

# revision identifiers, used by Alembic.
revision = 'b68a4f5e063d'
down_revision = '9e98fc383784'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ups_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oid_dict', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('vendeor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ups_info')
    ### end Alembic commands ###
