"""empty message

Revision ID: bc72c09617b3
Revises: d5faf887fb48
Create Date: 2016-08-20 23:27:52.239177

"""

# revision identifiers, used by Alembic.
revision = 'bc72c09617b3'
down_revision = 'd5faf887fb48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    ### end Alembic commands ###
