"""empty message

Revision ID: bc75b6256aa7
Revises: e14ced237c6a
Create Date: 2016-08-14 23:42:52.262572

"""

# revision identifiers, used by Alembic.
revision = 'bc75b6256aa7'
down_revision = 'e14ced237c6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('permit_value', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'permit_value')
    ### end Alembic commands ###
