"""empty message

Revision ID: c29758e271be
Revises: 994fdbd937fc
Create Date: 2016-12-04 15:40:07.847877

"""

# revision identifiers, used by Alembic.
revision = 'c29758e271be'
down_revision = '994fdbd937fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_record', sa.Column('expire', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_record', 'expire')
    ### end Alembic commands ###
