"""empty message

Revision ID: cabd21f4dbcd
Revises: e5e9a2163ace
Create Date: 2016-08-04 00:19:39.867875

"""

# revision identifiers, used by Alembic.
revision = 'cabd21f4dbcd'
down_revision = 'e5e9a2163ace'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('area', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'area')
    ### end Alembic commands ###
