"""empty message

Revision ID: cfc16a7cc692
Revises: 73235d8cd3b1
Create Date: 2016-12-03 22:35:06.963711

"""

# revision identifiers, used by Alembic.
revision = 'cfc16a7cc692'
down_revision = '73235d8cd3b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_record_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNum', sa.String(length=20), nullable=True),
    sa.Column('respCode', sa.String(length=10), nullable=True),
    sa.Column('callId', sa.String(length=40), nullable=True),
    sa.Column('createDateInResp', sa.String(length=15), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_record_detail_callId'), 'call_record_detail', ['callId'], unique=False)
    op.create_index(op.f('ix_call_record_detail_createDateInResp'), 'call_record_detail', ['createDateInResp'], unique=False)
    op.create_index(op.f('ix_call_record_detail_phoneNum'), 'call_record_detail', ['phoneNum'], unique=False)
    op.create_index(op.f('ix_call_record_detail_respCode'), 'call_record_detail', ['respCode'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_record_detail_respCode'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_phoneNum'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_createDateInResp'), table_name='call_record_detail')
    op.drop_index(op.f('ix_call_record_detail_callId'), table_name='call_record_detail')
    op.drop_table('call_record_detail')
    ### end Alembic commands ###
