"""empty message

Revision ID: d586be46fe27
Revises: aa9c107bbfac
Create Date: 2016-08-15 00:37:57.606245

"""

# revision identifiers, used by Alembic.
revision = 'd586be46fe27'
down_revision = 'aa9c107bbfac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_machine_room', sa.Column('permit_machine_room', sa.Integer(), nullable=False))
    op.alter_column('area_machine_room', 'area_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_area_machine_room_area_id'), 'area_machine_room', ['area_id'], unique=False)
    op.drop_column('area_machine_room', 'machine_room_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_machine_room', sa.Column('machine_room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_area_machine_room_area_id'), table_name='area_machine_room')
    op.alter_column('area_machine_room', 'area_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('area_machine_room', 'permit_machine_room')
    ### end Alembic commands ###
