"""empty message

Revision ID: d5faf887fb48
Revises: d586be46fe27
Create Date: 2016-08-16 01:22:28.487360

"""

# revision identifiers, used by Alembic.
revision = 'd5faf887fb48'
down_revision = 'd586be46fe27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=30), nullable=False),
    sa.Column('area_desc', sa.String(length=200), nullable=True),
    sa.Column('area_machine_room', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_area_name'), 'area', ['area_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_area_name'), table_name='area')
    op.drop_table('area')
    ### end Alembic commands ###
