"""empty message

Revision ID: d65dd2b49ad0
Revises: 75ccae4a5d08
Create Date: 2016-07-24 17:28:03.364059

"""

# revision identifiers, used by Alembic.
revision = 'd65dd2b49ad0'
down_revision = '75ccae4a5d08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mac_learned_by_ont', sa.Column('test', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mac_learned_by_ont', 'test')
    ### end Alembic commands ###
