"""empty message

Revision ID: d699bcd07913
Revises: 587d599dc829
Create Date: 2016-08-14 23:33:17.801640

"""

# revision identifiers, used by Alembic.
revision = 'd699bcd07913'
down_revision = '587d599dc829'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('permit_value', sa.Binary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'permit_value')
    ### end Alembic commands ###
