"""empty message

Revision ID: de46d1de0b70
Revises: b68a4f5e063d
Create Date: 2016-12-09 23:04:31.215033

"""

# revision identifiers, used by Alembic.
revision = 'de46d1de0b70'
down_revision = 'b68a4f5e063d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ups_info', sa.Column('name', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ups_info', 'name')
    ### end Alembic commands ###
