"""empty message

Revision ID: e14ced237c6a
Revises: d699bcd07913
Create Date: 2016-08-14 23:42:26.883994

"""

# revision identifiers, used by Alembic.
revision = 'e14ced237c6a'
down_revision = 'd699bcd07913'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineroom_list', 'permit_value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machineroom_list', sa.Column('permit_value', sa.BLOB(), nullable=True))
    ### end Alembic commands ###
