"""empty message

Revision ID: e5e9a2163ace
Revises: 644c576a4edc
Create Date: 2016-08-03 14:50:03.727327

"""

# revision identifiers, used by Alembic.
revision = 'e5e9a2163ace'
down_revision = '644c576a4edc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('duty', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'duty')
    op.drop_column('users', 'area')
    ### end Alembic commands ###
