"""empty message

Revision ID: f24fa64b1859
Revises: de46d1de0b70
Create Date: 2016-12-13 08:50:52.446221

"""

# revision identifiers, used by Alembic.
revision = 'f24fa64b1859'
down_revision = 'de46d1de0b70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ups_info', sa.Column('community', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ups_info', 'community')
    ### end Alembic commands ###
